import type { Track } from './types'
import { getArtworkUrl } from './youtube'

export const SEED_TRACKS: Track[] = [
  {
    id: 'DWcJFNfaw9c',
    title: 'Lofi Hip Hop Radio - Beats to Relax/Study to',
    artist: 'Lofi Girl',
    album: 'Lofi Sessions',
    durationSeconds: 215,
    artworkUrl: getArtworkUrl('DWcJFNfaw9c', 'mq'),
    genre: 'Lo-Fi',
    year: 2024,
    source: 'youtube',
  },
  {
    id: '4xDzrJKXOOY',
    title: 'synthwave radio - chill / retro beats',
    artist: 'Lofi Girl Synthwave',
    album: 'Synthwave Dreams',
    durationSeconds: 198,
    artworkUrl: getArtworkUrl('4xDzrJKXOOY', 'hq'),
    genre: 'Synthwave',
    year: 2024,
    source: 'youtube',
  },
  {
    id: '5qap5aO4i9A',
    title: 'Lofi Cat Beats - Relaxing Purrs & Music',
    artist: 'CatChat Chill',
    album: 'Cat Whispers',
    durationSeconds: 240,
    artworkUrl: getArtworkUrl('5qap5aO4i9A', 'hq'),
    genre: 'Cat Beats',
    year: 2024,
    source: 'youtube',
  },
  {
    id: 'fJ9rUzIMcZQ',
    title: 'Bohemian Rhapsody',
    artist: 'Queen',
    album: 'A Night at the Opera',
    durationSeconds: 354,
    artworkUrl: getArtworkUrl('fJ9rUzIMcZQ', 'hq'),
    genre: 'Rock',
    year: 1975,
    source: 'youtube',
  },
  {
    id: 'hT_nvWreIhg',
    title: 'Counting Stars',
    artist: 'OneRepublic',
    album: 'Native',
    durationSeconds: 259,
    artworkUrl: getArtworkUrl('hT_nvWreIhg', 'hq'),
    genre: 'Pop',
    year: 2013,
    source: 'youtube',
  },
  {
    id: '4NRXx6U8ABQ',
    title: 'Blinding Lights',
    artist: 'The Weeknd',
    album: 'After Hours',
    durationSeconds: 200,
    artworkUrl: getArtworkUrl('4NRXx6U8ABQ', 'hq'),
    genre: 'Synthwave',
    year: 2020,
    source: 'youtube',
  },
  {
    id: '09R8_2nJtjg',
    title: 'Sugar',
    artist: 'Maroon 5',
    album: 'V',
    durationSeconds: 235,
    artworkUrl: getArtworkUrl('09R8_2nJtjg', 'hq'),
    genre: 'Pop',
    year: 2014,
    source: 'youtube',
  },
  {
    id: 'YQHsXMglC9A',
    title: 'Hello',
    artist: 'Adele',
    album: '25',
    durationSeconds: 295,
    artworkUrl: getArtworkUrl('YQHsXMglC9A', 'hq'),
    genre: 'Pop',
    year: 2015,
    source: 'youtube',
  },
  {
    id: 'OPf0YbXqDm0',
    title: 'Uptown Funk ft. Bruno Mars',
    artist: 'Mark Ronson',
    album: 'Uptown Special',
    durationSeconds: 270,
    artworkUrl: getArtworkUrl('OPf0YbXqDm0', 'hq'),
    genre: 'Pop',
    year: 2014,
    source: 'youtube',
  },
  {
    id: '3tmd-ClpJxA',
    title: 'Cat Lounge Chill Music',
    artist: 'Purrfect Harmony',
    album: 'Cat Chill Volume 1',
    durationSeconds: 184,
    artworkUrl: getArtworkUrl('3tmd-ClpJxA', 'hq'),
    genre: 'Cat Beats',
    year: 2024,
    source: 'youtube',
  },
  {
    id: 'SlPhMPnQ58k',
    title: 'Memories',
    artist: 'Maroon 5',
    album: 'JORDI',
    durationSeconds: 195,
    artworkUrl: getArtworkUrl('SlPhMPnQ58k', 'hq'),
    genre: 'Pop',
    year: 2019,
    source: 'youtube',
  },
  {
    id: 'nfs8NYg7yQM',
    title: 'Resonance',
    artist: 'HOME',
    album: 'Odyssey',
    durationSeconds: 212,
    artworkUrl: getArtworkUrl('nfs8NYg7yQM', 'hq'),
    genre: 'Synthwave',
    year: 2014,
    source: 'youtube',
  },
]

/**
 * Sentinel for "no genre filter". Kept out of `GENRES` as a value the UI can
 * compare against without hardcoding a Spanish word — it renders as `t.allGenres`.
 */
export const ALL_GENRES = '__all__'

export const GENRES = [ALL_GENRES, 'Pop', 'Rock', 'Lo-Fi', 'Synthwave', 'Cat Beats']
